name: Check code standarts
run-name: Check code standarts

on:
  workflow_dispatch
#   pull_request:
#     types: [opened, reopened, synchronize]
#     branches: [ "master", "dev" ]

permissions:
  contents: write

jobs:
  code_standarts:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      
      - name: Install PHP dependencies
        uses: lukekortunov/php-composer-install-and-cache@v1

      - name: PHP Code Standarts
        run: |
          chmod +x ./bin/phpcs.sh
          ./bin/phpcs.sh -full
        shell: bash
