name: Download
run-name: Download

on: [workflow_dispatch]
    
permissions:
  contents: write

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
      # Get composer cache directory
    -   id:     get-composer-cache-directory
        name:   Get Composer caches directory path
        run:    echo "dir=$(composer config cache-files-dir)" >> $GITHUB_OUTPUT
        shell:  bash

      # Mount cache directory
    -   id:     mount-cache-directory
        name:   Mount cache directory
        uses:   actions/cache@v3
        with:
            path:           ${{ steps.get-composer-cache-directory.outputs.dir }}
            key:            ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
            restore-keys:   ${{ runner.os }}-composer-
          
    - name: Build and zip project
      run: |
        chmod 777 ./bin/zip.sh
        sudo bash ./bin/zip.sh
      shell: bash
      
    - name: Add archive to artifacts
      uses: actions/upload-artifact@v3
      with:
        name: reepay-woocommerce-payment.zip
        path: ./build/reepay-woocommerce-payment.zip
